# Generated by Django 5.2.4 on 2025-07-22 08:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_slab_grams', models.PositiveIntegerField(help_text='The upper limit for this weight slab in grams (e.g., 500 for 0-500g).', unique=True)),
                ('regional_rate', models.DecimalField(decimal_places=2, help_text="Shipping cost for within the artisan's state/region.", max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('national_rate', models.DecimalField(decimal_places=2, help_text='Shipping cost for the rest of India.', max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
            ],
            options={
                'ordering': ['weight_slab_grams'],
            },
        ),
    ]
