# Generated by Django 5.2.4 on 2025-07-25 11:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingrate',
            name='metro_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Cost for shipping between metro cities (e.g., average of Zone C).', max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='shippingrate',
            name='national_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Cost for shipping to the rest of India (e.g., average of Zone D).', max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='shippingrate',
            name='regional_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Cost for local/regional shipping (e.g., average of Zone A & B).', max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='shippingrate',
            name='weight_slab_grams',
            field=models.PositiveIntegerField(help_text='The upper weight limit for this slab in grams (e.g., 500 for 0-500g).', unique=True),
        ),
    ]
