# Generated by Django 5.2.4 on 2025-07-22 10:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_approved_artisan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artisanprofile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='buyerprofile',
            name='saved_items',
        ),
        migrations.AddField(
            model_name='artisanprofile',
            name='account_holder_name',
            field=models.CharField(blank=True, help_text='Full name as it appears on the bank account.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='artisanprofile',
            name='bank_account_number',
            field=models.CharField(blank=True, help_text='Your complete bank account number.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='artisanprofile',
            name='bank_name',
            field=models.CharField(blank=True, help_text='The name of your bank (e.g., State Bank of India).', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='artisanprofile',
            name='ifsc_code',
            field=models.CharField(blank=True, help_text='The 11-character IFSC code of your bank branch.', max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='artisanprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisanprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='artisan_profile/'),
        ),
        migrations.AlterField(
            model_name='buyerprofile',
            name='location',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
    ]
