# Generated by Django 5.2.4 on 2025-07-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_wishlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(default='Default Address'),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='City', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='full_name',
            field=models.CharField(default='Unnamed', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=15),
        ),
        migrations.AddField(
            model_name='order',
            name='postal_code',
            field=models.CharField(default='000000', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(default='State', max_length=50),
        ),
    ]
