# Generated by Django 5.2.4 on 2025-07-22 07:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_category_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='height_in_cm',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Height of the package in centimeters', max_digits=6),
        ),
        migrations.AddField(
            model_name='product',
            name='length_in_cm',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Length of the package in centimeters', max_digits=6),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_in_grams',
            field=models.PositiveIntegerField(default=500, help_text='Weight of the packaged item in grams (e.g., 500 for 0.5 kg)'),
        ),
        migrations.AddField(
            model_name='product',
            name='width_in_cm',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Width of the package in centimeters', max_digits=6),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category'),
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
